### ISSUE TITLE
how to use it in nuxt3.like this example but not work.

### ISSUE THREAD

**Issue by tenfei4** [jerrywu001/vue3-toastify#1]
in @/plugins/vue3toastify.client.ts

import Vue3Toasity from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(Vue3Toasity,
        {
            autoClose: 3000,
        },
    );
})

**Comment by jerrywu001** [comment]
It's a problem, I use `reactive` API to save global options, but it does not support SSR;

But, You can use the `updateGlobalOptions` function to change global options.

Just **remove the plugins** above. Then use the `updateGlobalOptions` function.

```vue
<template>
  <div>
    <div style="margin: 0 auto; width: 600px;">
      <button @click="notify">notify</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { toast, updateGlobalOptions } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

updateGlobalOptions({ autoClose: 1000 });

const notify = () => {
  toast.success("Success Notification !", {
    position: toast.POSITION.TOP_RIGHT,
  });
};
</script>
```

It takes effect.

**Comment by jerrywu001** [comment]
By now, no support for using Plugin with SSR. Use `updateGlobalOptions` to change global options in Vue single file instead.

**Comment by jerrywu001** [comment]
It can use in nuxt3. There is an online demo:

https://stackblitz.com/edit/nuxt-starter-1gszqs?file=plugins%2Fvue3-toastify.ts,app.vue
