### ISSUE TITLE
Toasts not displaying after clearAll is called and limit set

### ISSUE THREAD

**Issue by esemplare** [jerrywu001/vue3-toastify#13]
Steps to reproduce:

1. Navigate to https://vue3-toastify.js-bridge.com/
2. Set limit to 5
3. Click 'normal toast' 5 times
4. Click 'unmount all container' (e.g. toasts.clearAll())
5. Before the animation completes, repeatedly click 'normal toast'
6. Toasts are no longer displayed

We have toasts being created asynchronously (not user driven interaction) and when clearAll is called by the user there appears to be a race condition where the toast is queued but there are no toast containers. This prevents toasts from being displayed from subsequent toast calls.

I've logged inside openToast and watingForQueue and seen that once this condition occurs, displayedCount is 0, queue.items.length > 0. There is a main condition in openToast that checks if the queue is empty, and if so, only then it will append the toast.

```
// toast.tsx L69

else if (!queue.items.length) {
  doAppend(content, options);
}
```

In general we've also found other instances where limit is not being respected (showing more or less than configured). Will report issues when a reproducible test is found for those cases.

**Comment by jerrywu001** [comment]
thanks
