### ISSUE TITLE
word-break sometimes

### ISSUE THREAD

**Issue by zuo305** [jerrywu001/vue3-toastify#14]
Hi , could we do some settings to avoid the word break? Thanks.

![Untitled](https://user-images.githubusercontent.com/4032158/224621254-c0bdfc00-d481-4746-b0df-381e8a1fdbec.jpg)

**Comment by jerrywu001** [comment]
Released v0.1.5

**Comment by zuo305** [comment]
Awesome, it is working now. Thanks a lot.
