### ISSUE TITLE
Issue making a standalone Nuxt wrapper

### ISSUE THREAD

**Issue by laurent-treguier-with** [jerrywu001/vue3-toastify#16]
Hello!
At my company we're looking to make a reusable [Nuxt module for this](https://github.com/ModelW/toast-ts/tree/develop), using the example provided in the `README.md`.
When trying to package it however, I get the following error:
```
npm ERR! src/runtime/plugin.ts(5,1): error TS4082: Default export of the module has or is using private name 'ToastPromiseParams'.
```

I do [see in the code](https://github.com/jerrywu001/vue3-toastify/blob/a7adcf26ad14f2c87faf1e5b9dc9b5221d870cbc/src/core/toast.tsx#L188) that `ToastPromiseParams` is already exported though... So I'm not sure what the root of the problem is (or if something even can be changed in this repo to fix it).

Steps to reproduce:
```shell
git clone https://github.com/ModelW/toast-ts
cd toast-ts
npm ci
npm run dev:build
npm pack
```

**Comment by jerrywu001** [comment]
> ToastPromiseParams

Something error with the build. You can modify the `vue3-toastify/index.d.ts` with `patch-package`, and add the `export` keyword.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/12525415/232366259-7e8257de-9a19-43fd-adde-3acda8975ec2.png">

Then re-run `npm pack`
