### ISSUE TITLE
Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by rankill** [jerrywu001/vue3-toastify#17]
Cannot make it work in vue3 project, it was working some days ago, some hint? 

Error  in ./node_modules/vue3-toastify/dist/esm/index.js

Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
| }
| function oe(e) {
>   return (se(e.content) ? T(e.content.props) : null) ?? T(e.data ?? {});
| }
| function Fe(e) {
```

 @ ./src/main.ts 16:0-52 97:10-22 98:14-19 100:11-16
 @ multi (webpack)-dev-server/client?http://192.168.1.55:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by jerrywu001** [comment]
I'm sorry, but I'm currently on vacation. I'll fix it in a few days.

You can temporarily use the previous version.
