### ISSUE TITLE
I found a other way for use it in nuxt3.

### ISSUE THREAD

**Issue by tenfei4** [jerrywu001/vue3-toastify#2]
file: @/plugins/vue3-toastify.client.ts
------------------------------------------------
`import toastify, { toast } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';
const options = {
    position:'top-center',//top-left,top-center,top-right,bottom-left,bottom-center,bottom-right
    autoClose:4000,
    hideProgressBar:true,
    closeButton:true,
    theme:'auto',//auto,colored,dark,light
    transition:'bounce',//bounce,flip,slide,zoom
    pauseOnFocusLoss:true,
    pauseOnHover:true,
    rtl:false,
    style: {
      opacity: '0.95',
      userSelect: 'none',
      zIndex:'20'
    },
  };

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(toastify,options);
  return {provide:{toast}};
})`

any view page 
----------------------------------
useNuxtApp().$toast.info('toastify success');
or
this.$toast.success('toastify is word');

**Comment by jerrywu001** [comment]
It can use in nuxt3. There is an online demo:

https://stackblitz.com/edit/nuxt-starter-1gszqs?file=plugins%2Fvue3-toastify.ts,app.vue

**Comment by jerrywu001** [comment]
It can use in nuxt3. There is an online demo:

https://stackblitz.com/edit/nuxt-starter-1gszqs?file=plugins%2Fvue3-toastify.ts,app.vue
