### ISSUE TITLE
Using 'limit' param can break promise toasts

### ISSUE THREAD

**Issue by oldskool73** [jerrywu001/vue3-toastify#20]
Demo: 
Notice the promise modals do not close until removed and restarted manually.
https://jam.dev/c/628dd8da-b239-46ab-afc4-db5d063a5f26

Reproduce:
- Go to the demo page @ https://vue3-toastify.js-bridge.com/
- Set the 'Limit' to something, e.g. 5 (doesn't matter what as long as it's set)
- Press the 'with promise' button
- While the promise toasts are open, press the 'normal toast' button several times, so the queued toasts exceed the limit number

Expected:
Queued toasts show, and the promise toasts complete

Actual:
Queued toasts show, but the promise toasts never complete

Notes:
Appears to require a combination of limit + promise + normal + a queue/backlog of toasts to cause the issue.

**Comment by jerrywu001** [comment]
@0.10.11
