### ISSUE TITLE
Using vuetify components inside a custom component "Failed to resolve component"

### ISSUE THREAD

**Issue by Behave81** [jerrywu001/vue3-toastify#22]
In my project I have installed and configured vuetify correct and it is working everywhere.
But when I use some vuetity components inside a Toast component I get the error "**Failed to resolve component: v-card**"

component:
```
<template>
	<div>
		<v-card title="title"> </v-card>
	</div>
</template>

<script setup lang="ts">
	import { PropType } from "vue";
	import type { ToastOptions } from "vue3-toastify";
	defineProps({
		closeToast: {
			type: Function as PropType<(e?: MouseEvent) => void>,
			required: true,
		},
		toastProps: {
			type: Object as PropType<ToastOptions>,
			required: true,
		},
	});
</script>

<style scoped></style>
```

call of the custom compnent:
```
import ToastComponent from "./ToastComponent.vue";

export function failure(message: string, error: any) {
	toast(ToastComponent, {
		closeOnClick: false,
		position: toast.POSITION.BOTTOM_CENTER,
		data: error,
		type: toast.TYPE.ERROR,
		autoClose: false,
	});
}
```

How can I use vuetify components inside a custom toast component?

**Comment by jerrywu001** [comment]
@Behave81  can you provide me an online demo with https://stackblitz.com/

**Comment by goktugerol-dev** [comment]
You can directly use it in under axios instead of using as a different component, which will give the same result regardless of whatever tool you use in the template.

**Comment by jerrywu001** [comment]
@Behave81 @goktugerol-dev

The reason why we can't parse the `v-card` is `h` function in `vue3` can't resolve a global component, like `register by vuetify`:

```html
import { createApp } from 'vue';
import Vue3Toasity, { type ToastContainerOptions } from 'vue3-toastify';
import App from './App.vue';

import 'vuetify/styles';
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components;
import * as directives from 'vuetify/directives';

const vuetify = createVuetify({
  components,
  directives,
});

const app = createApp(App);
app.use(vuetify);

app.use(
  Vue3Toasity,
  {
    // rtl: true,
  } as ToastContainerOptions,
);

app.mount('#app');
```

```tsx
import { defineComponent, h } from 'vue';

const Child = defineComponent({
  name: 'Child',
  setup() {
    return () => h('v-card', [h('span', 'hello')]);
  },
});

export default Child;
```

**result:**

![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/69b93dca-3cd1-4ab8-9a76-3429a57a96a4)

**Comment by jerrywu001** [comment]
you must import what you use

**Comment by firecrauter** [comment]
In my case I had two apps (different package.json) using toast. One of only custom components.
For some reason, when one used toast, the other couldn't.

**My solution:**

### main.ts (top-first app)
```
import 'vue3-toastify/dist/index.css';
import Vue3Toastify, { toast, type ToastContainerOptions } from 'vue3-toastify';
(window as any).toast = toast;
app.use(Vue3Toastify, {
     autoClose: 3000, theme: "dark"
} asToastContainerOptions);
```

### (second app)
shared/getGlobalToast.ts
```
import { toast } from "vue3-toastify";
export function getGlobalToast() {
    if ((window as any).toast == null) return toast;
    type MY_TYPE = typeof toast;
    return (window as any).toast as MY_TYPE;
}
```

### (anywhere in second app)
```import { getGlobalToast } from '@/getGlobalToast';
  getGlobalToast().success(`...`);
  ```
  
  Luckily the Typo is not lost

**Comment by yulei199719** [comment]
focus

**Comment by emsyzz** [comment]
Issue is due to fact that toast messages are rendered in completely separate Vue application that does not share context with your application - no global components, no globalProperties, no nothing. All plugins, directives, components and other stuff, must be be imported and configured again.
https://github.com/jerrywu001/vue3-toastify/blob/54773b9be133070b8cd7eaab310b5fa299fa1e13/src/store/toastContainers.ts#L121

I was hopeful that placing toast container (element with ID same as `options.containerId`) within DOM of main Vue application would somehow let Toastify to hook into it but tough luck - it doesn't.

Some similar plugins (modals and such) provide container component to insert somewhere in main application's layout and then renders their stuff inside it, which allows accessing main application context from within component that is provided to plugin and it works out really nicely.

**Comment by jerrywu001** [comment]
from 0.2.6

```tsimport { App, createApp } from 'vue';
import router from './routes';

import Vue3Toasity, { type ToastContainerOptions } from 'vue3-toastify';

import Root from './App.vue';

import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/reset.css';

function resolveGLobalComponents(instance: App<Element>) {
  instance.use(Antd);
}

const app = createApp(Root);

app.use(router);

resolveGLobalComponents(app);

app.use(
  Vue3Toasity,
  {
    // the Toast application is separate from the main application, so we need to call .use
    useHandler: resolveGLobalComponents,
    // other props...
  } as ToastContainerOptions,
);

app.mount('#app');
```
