### ISSUE TITLE
How to install in main.js? not in main.ts

### ISSUE THREAD

**Issue by Gabrielnotus** [jerrywu001/vue3-toastify#23]
I am triyng to install in vue3 project without typescript but it doesnt works. The images show the problem.

I **cant** use main.ts. 

I will be very grateful if you show me how to use in a SFC component with the correct import in the main.js

Thanks for help.

![Captura de pantalla 2023-06-01 154150](https://github.com/jerrywu001/vue3-toastify/assets/123084821/a06f041c-cf5a-45bc-8bc6-618a5b1f7714)
![Captura de pantalla 2023-06-01 154212](https://github.com/jerrywu001/vue3-toastify/assets/123084821/44a9001e-b919-4950-b5ad-3b82844799a9)

**Comment by Eliophot** [comment]
Hello,

Like this : 

```js
import { createApp } from 'vue'
import App from './App.vue'
import Vue3Toasity from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';
const ToastContainerOptions = {
    autoClose: 3000
}
const app = createApp(App)
app.use(Vue3Toasity, ToastContainerOptions)
app.mount('#app')
```

**Comment by jerrywu001** [comment]
Answered

**Comment by jerrywu001** [comment]
> I am trying to use in SFC component as: this.$toast and return undefined, why?

@Gabrielnotus 

Sorry, `.use` can only register the global settings. You need to import the `toast`.

```vue
<script>
import { toast } from 'vue3-toastify';

const showHandler = () => {
  toast('hello world');
};
<script>
```
