### ISSUE TITLE
微信浏览器环境下，提示框打开瞬间消失

### ISSUE THREAD

**Issue by tenfei4** [jerrywu001/vue3-toastify#24]
在微信小程序和公众号环境下使用，无论使用全局设置autoClose还是调用时设置，都会出现  “打开提示框体” 一瞬间就消失的问题，还有修复一下。

**Comment by jerrywu001** [comment]
我尝试了下，并没有复现，请描述下具体操作步骤~

**Comment by tenfei4** [comment]
在chrome、firefox、edge下均正常，微信浏览器PC版的也是正常的，仅仅是微信浏览器手机移动端会出现这个问题。
`
useNuxtApp().$toast.success('订单已确认！');
useNuxtApp().$toast.success('订单已完成！',{autoClose:3000});
`
以上这两种情况 都会出现瞬间消失的问题，但仅限微信手机移动端出现。

**Comment by tenfei4** [comment]
你可以尝试用手续微信浏览器访问 [http://www.anongye.com/test](http://www.anongye.com/test)

**Comment by jerrywu001** [comment]
> 你可以尝试用手机微信浏览器访问 http://www.anongye.com/test

不好意思，还是无法复现


https://github.com/jerrywu001/vue3-toastify/assets/12525415/461b4af3-746d-4fd9-88ec-d448c7ac7990


https://github.com/jerrywu001/vue3-toastify/assets/12525415/69688ff9-e953-4954-91fd-d6f899eb8824

**Comment by jerrywu001** [comment]
我观察了一下你的页面，你的页面会间隔几秒重新reload，这样toastify肯定会消失的。

**Comment by jerrywu001** [comment]
> 我观察了一下你的页面，你的页面会间隔几秒重新reload，这样toastify肯定会消失的。

重新刷新的原因：
![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/b033c586-05ef-4f67-a440-aa6be4b67c31)

**Comment by tenfei4** [comment]
间隔刷新是因为这个地址处在开发模式下，是在修改内容时会websocket接收数据是刷新的。我试了两个手机均存在该问题，但都是ios系统，我再找一个android试一下。

**Comment by tenfei4** [comment]
真是一个神奇的问题，我找了几个朋友帮着测试，大部分是正常的，极少一部分不正常，会出现提示框瞬间消失，就好像是把autoClose:100 这样的效果，出问题的浏览端 安卓 华为 苹果 均有，但多数是正常的。。。。
