### ISSUE TITLE
can it be in 1 file?

### ISSUE THREAD

**Issue by fedottt** [jerrywu001/vue3-toastify#25]
hi
where i can get 1 file of this plugin? 
i use vue like src=../js/vue.js in plain js, without any frameworks or builders
and my project is local, without internet
with npm it didnt work, many errors when i try to use like src='"../" because it use many import without .js

**Comment by jerrywu001** [comment]
- download those files from cdn to local, like this:

![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/12a9e918-1275-4e9a-9437-900a70330dbe)

1. https://cdn.jsdelivr.net/npm/vue3-toastify@0.1.11/dist/index.css    ----> `toastify.js`
2. https://cdn.jsdelivr.net/npm/vue3-toastify@0.1.11/+esm                ----> `toastify.css`
3. https://unpkg.com/vue@3/dist/vue.esm-browser.js                         ----> `vue-esm.js`

TIPS!!!!: Edit `toastify.js`, replace `/npm/vue@3.3.4/+esm` with `/vue-esm.js`

- create a test.html
```html
<html lang="en">
<head>
  <link href="/toastify.css" rel="stylesheet" />
  <title>Using the ES Module Build</title>
</head>
<body>
  <div id="app">
    <button @click="notify">show toast</button>
  </div>
  <script type="module">
    import { createApp } from '/vue-esm.js'
    import { toast } from '/toastify.js';

    createApp({
      methods: {
        notify() {
          toast.info('hello', { rtl: true });
        },
      }
    }).mount('#app')
  </script>
</body>
</html>
```

- right click test.html with vscode live server
![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/50ed022d-d864-4758-9342-00bdd04ec4a1)

- open chrome, access http://127.0.0.1:5500/test.html
- success
![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/bbb059a0-55f3-4aec-9e99-03e8383cc32e)

**Comment by fedottt** [comment]
thank you) 
work well)

**Comment by ChaStPierre** [comment]
Follow-up question: how would this work if I already have vue3 using vue.global.js or prod versions?
Thanks
