### ISSUE TITLE
 A plugin must either be a function or an object with an "install" function.

### ISSUE THREAD

**Issue by npmrun** [jerrywu001/vue3-toastify#28]
按照您的代码：
```
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(Vue3Toastify, { 
        autoClose: 1000, 
        hideProgressBar: true, 
        clearOnUrlChange: false 
    })
    return {
        provide: { toast },
    }
})
```

然后`nuxt build`之后，运行`node .output/server/index.mjs`
会提示 A plugin must either be a function or an object with an "install" function.
因为Vue3Toastify变成了下面这样，
![image](https://github.com/jerrywu001/vue3-toastify/assets/62639956/1b2d1df5-c23c-4f13-86d6-0e1571ca698f),
开发时本来是这样的：
![image](https://github.com/jerrywu001/vue3-toastify/assets/62639956/b5b114e4-ca2d-45ce-b832-69d31ac8e9f1)
所以代码改成这样就不报警告了：
```
export default defineNuxtPlugin((nuxtApp) => {
    // @ts-ignore
    nuxtApp.vueApp.use(Vue3Toastify.default || Vue3Toastify, { 
        autoClose: 1000, 
        hideProgressBar: true, 
        clearOnUrlChange: false 
    })
    return {
        provide: { toast },
    }
})
```

想知道这种情况您有什么更好的办法吗,您那个stackblitz的示例也有这个问题

**Comment by jerrywu001** [comment]
@npmrun 没出现你说的问题，我用的是nuxt3.6.1, [stackblitz demo](https://stackblitz.com/edit/nuxt-starter-1gszqs)也是可以的

你把你的node版本, nuxt版本截图我看看

**Comment by npmrun** [comment]
版本：
```bash
$ node -v
v18.16.0
$ npm -v
9.5.1
```
我重新下载 [stackblitz demo](https://stackblitz.com/edit/nuxt-starter-1gszqs)之后也是一样的，步骤：
1. `npm install`
2. `npm run build`
3. `node .output/server/index.mjs`
4. 浏览器打开`http://localhost:3000/`，此时终端会出现如下信息：
![image](https://github.com/jerrywu001/vue3-toastify/assets/62639956/408c8fd9-270a-46b1-b01b-c77ba3e85134)

**Comment by jerrywu001** [comment]
没注意看，确实有warning，但是不影响实际结果，明天改成函数形式看看

**Comment by npmrun** [comment]
好像是的，我看.output/server中的node_modules中的vue3-toastify只有dist/index.js文件

我尝试在/node_modules增加了esm文件，并将其vue3-toastify的main字段改成"./dist/esm/index.mjs",此时再执行就是正常的了。

这是结果
![image](https://github.com/jerrywu001/vue3-toastify/assets/62639956/9743d9ec-d1c0-4fbf-80b6-5c5ec093f46d)

**Comment by jerrywu001** [comment]
暂时可以忽略warning, 先关闭
