### ISSUE TITLE
Feature request: Persistant toaster when page changes

### ISSUE THREAD

**Issue by Mostafa-Shalaby** [jerrywu001/vue3-toastify#29]
Hello, 
I have used this library in multiple of my own projects, and have found to be truely the perfect solution for my needs except for one thing.

When the page URL `window.location.href` changes, the toasters are all cleared. I want a way to disable this. Since i do want the toaster to persist in my application especially when i am navigating with vue router using `router.push` (It's not a page reload).

An example scenario is for example when logging in a user,
On successful login i want to show a toaster that will remain as they are being navigated away from login and to the homepage for example.

Current behaviour would clear the toaster the min a change in  `window.location.href` occurs.

Can this be added as an toast option?

**Comment by jerrywu001** [comment]
#27
