### ISSUE TITLE
Issue on Promise Toast in TOP position 

### ISSUE THREAD

**Issue by VanstraelenMickael** [jerrywu001/vue3-toastify#34]
Hi, 

I really like your component and I wanted to go next level and use the Promise feature for the app I'm working on.
I have a weird issue and I don't really a way of solving it without having your help.

In my component MyAccount.vue, I've a form with user information and the user can update his infos.

There is a Promise since i'm using an API.

If the toast is on the bottom there is no issue, but when the toast is on the top, there is the rainbow color on the top of the toast.
Can't really use that in my app, sometime the same issue appear on your demo and I have the same issue when I edit your documentation :

https://vue3-toastify.js-bridge.com/usage/promise.html#toast-promise

```
toast.promise(
    resolveAfter3Sec,
    {
      pending: 'Promise is pending',
      success: 'Promise resolved 👌',
      error: 'Promise rejected 🤯',
    },
    {
      position: toast.POSITION.TOP_RIGHT,
      transition: toast.TRANSITIONS.FLIP
    },
  );
```

https://github.com/jerrywu001/vue3-toastify/assets/11020188/0d5a0063-4297-4bd8-9b77-8070623a0500
https://github.com/jerrywu001/vue3-toastify/assets/11020188/ec4025bb-7500-425d-a5ec-394cd7aa3371

Would be an awesome fix.

Thank you.
Don't hesitate if I can be of any help.

**Comment by jerrywu001** [comment]
Sorry, I can not reproduce it.

**Comment by VanstraelenMickael** [comment]
I noticed it doesn't always happen but it does.
All I changed to your demo code is the position to TOP and I noticed it happens when the transition is set to FLIP

As you can see in my video, the bug doesn't always happens but it does.

https://github.com/jerrywu001/vue3-toastify/assets/11020188/1cc2edb4-5151-4b69-8738-8619855dac2b

Thank you
