### ISSUE TITLE
Toastify stops working when routing

### ISSUE THREAD

**Issue by DigiConvent** [jerrywu001/vue3-toastify#35]
When routing inside the vue3 app, the toasts dissapear with the page and if the new page triggers a new toast, it won't be shown. I have set the `clearOnUrlChange: true` but this doesn't trigger (fast enough?). I am working with page transitions in vue3. Is there something I'm missing?

**Comment by jerrywu001** [comment]
`clearOnUrlChange` default is `true`，means auto clear all toast when route/url change. your scene need set `clearOnUrlChange` to `false`.

**Comment by DigiConvent** [comment]
@jerrywu001  you're right, I'm so dumb... 🤦🏼‍♂️
