### ISSUE TITLE
Text on multiline or HTML

### ISSUE THREAD

**Issue by demiro** [jerrywu001/vue3-toastify#4]
So I would like to have a more complicated toast msg than just a text...
How can I do a multiline msg? like
`toast.success("Your registration was successfull!\n\nYou can log-in now")`

I would not actually do that, but it's an example... I have many occasions to use multiline msg

also sometimes I would like to use some HTML inside like
`toas.success("You have topped-up your account\nYour new balance is <b>10,000</b> sausages");`

Is  there a way to do it?

**Comment by jerrywu001** [comment]
version 0.0.5.

```jsx
toast.info("Hello World.\n I am <b>Tom</b>", { dangerouslyHTMLString: true });
```

**Comment by jerrywu001** [comment]
docs:
https://vue3-toastify.netlify.app/usage/render-html-string.html
