### ISSUE TITLE
Persist toasts across router changes

### ISSUE THREAD

**Issue by JenBerry** [jerrywu001/vue3-toastify#40]
Hello. Nice Toast but...

I'm using Nuxt3 SPA, and when I change the route with `router.push("/")` then any toasts close immediately rather than waiting for the set timeout.
- It happens even if I call the toast from the root app, not from within a page.
- It also happens even if I set `autoClose` to `false`

Is there a way to persist the toasts so they don't close when the route changes?

Thanks

**Comment by JenBerry** [comment]
Never mind I found the setting in the options XD

**Comment by jamus** [comment]
Hey @JenBerry would you mind pointing me to the setting?  😅

**Comment by JenBerry** [comment]
> Hey @JenBerry would you mind pointing me to the setting? 😅

You can specify `clearOnUrlChange` in the options - details here: https://vue3-toastify.js-bridge.com/api/container.html

Here's an excerpt from my code (Im working in TypeScript using Nuxt so this is me defining the plugin for nuxt):

```ts
import Vue3Toastify, { type ToastContainerOptions } from "vue3-toastify";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Vue3Toastify, {
    hideProgressBar: true,
    theme: "colored",
    clearOnUrlChange: false,
  } as ToastContainerOptions);
});
```

**Comment by joelxr** [comment]
The toast option type definition do not have `clearOnUrlChange` maybe it should be added, I'm getting a TS error when using this option with the toast.

Type is defined here: https://github.com/jerrywu001/vue3-toastify/blob/ac0e3d9b8f1481876e90e86fb309fd4394807aa4/src/types.ts#L241
