### ISSUE TITLE
pauseOnFocusLoss do work

### ISSUE THREAD

**Issue by bublikOff** [jerrywu001/vue3-toastify#42]
It seams that pauseOnFocusLoss do work if window not focused when toast created. 
It does work if toast was created during window was active and loss focus during autoClose timeout
Was this how it was intended?

**Comment by jerrywu001** [comment]
Thanks.  It is designed that "`pauseOnFocusLoss` does not work if the window is not focused when toast is created]".

because:
when the window loses focus while the toast is created by program, it should be auto-closed.
