### ISSUE TITLE
config to show one at a time

### ISSUE THREAD

**Issue by jiblett1000** [jerrywu001/vue3-toastify#5]
Hello,

Unless I'm missing something in the docs, it would be great to have the option of only showing one notification at a time rather than stacking them.

**Comment by jerrywu001** [comment]
@jiblett1000

see version 0.0.7

docs: https://vue3-toastify.js-bridge.com/usage/disable-multiple.html

**Comment by jiblett1000** [comment]
@jerrywu001 Thanks Jerry, I'm using vue-toastification at this point, but I'm open to looking back into toastify for future projects! I appreciate the quick feature addition.

Using the demo in the link, I did have a thought though. I feel the default behavior should be to treat it more as a queue in the sense that If one is shown at a time, the "notify" button shouldn't dismiss the current toast but rather add it to the queue and be shown after the current one has ended.

Another thought...this isn't a feature I personally need ( I believe in only showing one notification at a time from a UX perspective), but a lot of other toast packages allow you to customize the number of toasts shown at once. Again, I don't need that feature, but maybe others would.

Anyhow, great work!

**Comment by jerrywu001** [comment]
> @jerrywu001 Thanks Jerry, I'm using vue-toastification at this point, but I'm open to looking back into toastify for future projects! I appreciate the quick feature addition.
> 
> Using the demo in the link, I did have a thought though. I feel the default behavior should be to treat it more as a queue in the sense that If one is shown at a time, the "notify" button shouldn't dismiss the current toast but rather add it to the queue and be shown after the current one has ended.
> 
> Another thought...this isn't a feature I personally need ( I believe in only showing one notification at a time from a UX perspective), but a lot of other toast packages allow you to customize the number of toasts shown at once. Again, I don't need that feature, but maybe others would.
> 
> Anyhow, great work!

ok, good idea.

**Comment by jerrywu001** [comment]
> @jerrywu001 Thanks Jerry, I'm using vue-toastification at this point, but I'm open to looking back into toastify for future projects! I appreciate the quick feature addition.
> 
> Using the demo in the link, I did have a thought though. I feel the default behavior should be to treat it more as a queue in the sense that If one is shown at a time, the "notify" button shouldn't dismiss the current toast but rather add it to the queue and be shown after the current one has ended.
> 
> Another thought...this isn't a feature I personally need ( I believe in only showing one notification at a time from a UX perspective), but a lot of other toast packages allow you to customize the number of toasts shown at once. Again, I don't need that feature, but maybe others would.
> 
> Anyhow, great work!

now use version 0.1.0 @jiblett1000
