### ISSUE TITLE
Routing hides toast instantly.

### ISSUE THREAD

**Issue by gelhein** [jerrywu001/vue3-toastify#52]
Hi,

Is there a reason why the toast code is hiding the toast when you do a route to another location in a project?
Can I configure the toast to defeat this "hide on route"-functionality? ;)

My current workaround:

```
setTimeout(function () { 
  toast("My Task...");
}, 1);
```

**Comment by jerrywu001** [comment]
same as #27

**Comment by gelhein** [comment]
great, thanks, but why is not (clearOnUrlChange: false) default behaviour?
