### ISSUE TITLE
Toasts do not persist through Nuxt 3 route changes

### ISSUE THREAD

**Issue by tremorris1999** [jerrywu001/vue3-toastify#53]
Navigating within a Nuxt 3 project will dismiss any toasts upon navigation. I'm not sure if this is a bug or if there a way to change this behavior.

I've reproduced this using a fork of your provided StackBlitz demo.
I simply added another page and changed routes in the `notify` function.

https://stackblitz.com/edit/nuxt-starter-jdqxs9?file=README.md

**Comment by jerrywu001** [comment]
same as #27

**Comment by tremorris1999** [comment]
Thank you. Apologies for not finding it myself.
