### ISSUE TITLE
Can the delete function be made asynchronous?

### ISSUE THREAD

**Issue by xinchen37** [jerrywu001/vue3-toastify#56]
Can the delete function be made asynchronous?

**Comment by jerrywu001** [comment]
?

**Comment by xinchen37** [comment]
> ?

https://codesandbox.io/p/sandbox/vue3-ts-forked-m3zj7z?file=%2Fsrc%2FApp.vue

toast.clearAll()
Not as expected, the later added TOAST is also removed

**Comment by jerrywu001** [comment]
![image](https://github.com/jerrywu001/vue3-toastify/assets/12525415/4bc5cccf-a98f-43b0-bcab-5cba6c103698)

@xinchen37

**Comment by xinchen37** [comment]
> ![image](https://private-user-images.githubusercontent.com/12525415/335004554-4bc5cccf-a98f-43b0-bcab-5cba6c103698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTA4NjQsIm5iZiI6MTcxNzA1MDU2NCwicGF0aCI6Ii8xMjUyNTQxNS8zMzUwMDQ1NTQtNGJjNWNjY2YtYTk4Zi00M2IwLWJjYWItNWNiYTZjMTAzNjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2MjkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1OTMyMWRlYjA1YTk3YmI3OGEzYmRjMGE0M2RiMTZiYjZjZGE1YzYxNmRkZDFkMWJlMzk3MWE5MDgzMmJjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3pVHGJZZBLouldA-i1SiBGZiItRx8qU02s3t6lSHBs)
> 
> @xinchen37

https://codesandbox.io/p/sandbox/vue3-ts-forked-m3zj7z?file=%2Fsrc%2FApp.vue%3A17%2C12&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrhzvlh00073b75rmfvc9c2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrhzvlh00033b75df6utm4b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrhzvlh00043b75stae08cc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrhzvlh00063b75n5z4u3pf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrhzvlh00033b75df6utm4b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrhzvlh00023b75w9m9oo13%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A12%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwrhzvlh00033b75df6utm4b%2522%252C%2522activeTabId%2522%253A%2522clwrhzvlh00023b75w9m9oo13%2522%257D%252C%2522clwrhzvlh00063b75n5z4u3pf%2522%253A%257B%2522id%2522%253A%2522clwrhzvlh00063b75n5z4u3pf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clwsvtv0u001c3b773cih3vn8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwsvtv0u001c3b773cih3vn8%2522%257D%252C%2522clwrhzvlh00043b75stae08cc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrhzvlh00043b75stae08cc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by xinchen37** [comment]
update url
https://codesandbox.io/p/sandbox/vue3-ts-forked-m3zj7z?file=%2Fsrc%2FApp.vue

**Comment by zuo305** [comment]
Same problem is here. Please resolve it. Thank you. @jerrywu001

**Comment by jerrywu001** [comment]
v0.2.2

**Comment by zuo305** [comment]
...I updated to the latest version v0.2.2. But the issue is the same.

**Comment by zuo305** [comment]
Hi @jerrywu001 I tried the latest version. It looks like the bug is still there, If it calls the clearAll or remove first, the next toast will disappear quickly.

**Comment by jerrywu001** [comment]
> Hi @jerrywu001 I tried the latest version. It looks like the bug is still there, If it calls the clearAll or remove first, the next toast will disappear quickly.

can you provide your code, please?

**Comment by zuo305** [comment]
Hi, @jerrywu001 , thanks for you replying. You can try this one: https://codesandbox.io/p/sandbox/vue3-ts-forked-m3zj7z?file=%2Fsrc%2FApp.vue%3A15%2C28

It is the same as the @xinchen37 used. It is already using 0.2.2.

when you click the test button, the second toast disappears very fast, it is not expected. The test2 is correct, but we have to sleep 2 seconds.
