### ISSUE TITLE
Auto theme detection not reliable when it depends on a classList value

### ISSUE THREAD

**Issue by joshuagraber** [jerrywu001/vue3-toastify#64]
This is a great package, thank you for maintaining @jerrywu001.

I have a small complaint on the auto theme detection.

It appears as though [these lines of code](https://github.com/jerrywu001/vue3-toastify/blob/96706e8399c336bd1d8c458cf872b6df395352a0/src/utils/tools.ts#L60-L62) assume that a user will be setting the theme as a classlist on the document element.

It would be more robust and user-friendly to detect theme from client theme preference, rather than forcing consumers of the package into the overhead of adding to the classlist of the document element.

Suggestion to use `window.matchMedia`, combined with listener for subsequent changes in theme preference, as it is more flexible for users.

**Comment by jerrywu001** [comment]
```ts
export function getSystemTheme(): ToastTheme {
  const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
  const customDark = document.documentElement.classList.contains('dark');

  return customDark ? 'dark' : prefersDark ? 'dark' : 'light';
}
```

The custom theme class should have a higher priority. When there is no 'dark' class on the html, the system theme change will be judged. I think this is more reasonable.
