### ISSUE TITLE
How to pass content to custom component

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#67]
So if I use a regular toast I do:
```js
$toast('This is a toast message', {
    type,
});
```
But If I use a custom component, how to I pass the custom content ? 
```js
$toast(AppToast, {
    type,
   content: 'This is a toast message',
});
```
I guess I could use a custom props ? 
```js
$toast(AppToast, {
    type,
    data: {
        msg: 'This is a toast message',
    },
});
```
But seems like the default content should be handled

**Comment by jerrywu001** [comment]
![image](https://github.com/user-attachments/assets/9c2776fe-f380-47b2-906f-07af9d7c4d86)


- constomCompo (define a prop named `data` to receive your custom props)

```html
<template>
  <div :style="`color: ${data.color}`">
    {{ data.title }}
  </div>
</template>

<script setup lang="ts">
import { PropType } from 'vue';

defineProps({
  data: {
    type: Object as PropType<{ title: string; color: String }>,
    default: () => ({}),
  },
});
</script>
```

- invoke like this (use data)

```ts
import { toast } from 'vue3-toastify';

toast(constomCompo, {
    type: 'success',
    data: {
      title: 'hello world',
      color: '#00a2ed',
    },
});
```

**Comment by mrleblanc101** [comment]
Ok, maybe the doc should be more clear about that. The only custom component exemple on the doc use static string. I find it odd that we cannot pass `content` at the root level to be displayed as the default `<slot>`

**Comment by jerrywu001** [comment]
thanks ,  I will improve the documentation

**Comment by jerrywu001** [comment]
You are right, data and props should be separated. 

1. Is it possible to call it like this?

```ts
toast(constomCompo, {
    type: 'success',
    contentProps: {
      title: 'hello world',
      color: '#00a2ed',
    },
});
```

2. Which of the following two custom component props definition forms do you prefer?

a. 

```ts
defineProps({
  contentProps: {
    type: Object as PropType<{ title: string; color: String }>,
    default: () => ({}),
  },
});
```

b. (**Some props of the toast app may override the props of your custom component with the same name**)
```ts
defineProps({
  title: {
    type: String,
    default: '',
  },
  color: {
    type: String,
    default: '',
  },
});
```

**Comment by mrleblanc101** [comment]
I'm not sure I understand the difference between `contentProps`, `toastProps` and `data`. 
I much prefer "b", where props are individually accessed.

I still think the default text should be able to be passed without using a custom props.
Something like:
```
$toast(AppToast, {
    type,
   content: 'This is a toast message',
});
```
But currently the "toastProps.content" is an object and does not contains the `content` string.
<img width="245" alt="Screenshot 2024-12-17 at 9 08 03 PM" src="https://github.com/user-attachments/assets/17fc153b-f442-4d4b-8e2b-fbd1feb49a36" />

**Comment by jerrywu001** [comment]
> But currently the "toastProps.content" is an object and does not contains the content string.

because the content is `AppToast` component.

I will follow `plan b` and complete the work~

If you want plan B to work later, you can set `expandCustomProps` to true

```ts
toast(constomCompo, {
    type: 'warning',
    expandCustomProps: true,
    contentProps: {
      title: 'hello world',
      color: '#00a2ed',
    },
  });
```

```html
<template>
  <div :style="`color: ${color}`">
    {{ title }}
  </div>
</template>

<script setup lang="ts">
import { PropType } from 'vue';

defineProps({
  title: {
    type: String,
    default: '',
  },
  color: {
    type: String,
    default: '',
  },
});
</script>
```

**Comment by jerrywu001** [comment]
will fininsh in next version

**Comment by mrleblanc101** [comment]
@jerrywu001 Alright, but why the term `contentProps` instead of simply `props` like [vue-toastification](https://github.com/Maronato/vue-toastification?tab=readme-ov-file#render-a-component-with-props-and-events) ?
Also is `contentProps` just a renamed `data` ?

**Comment by mrleblanc101** [comment]
I don't see anything about `contentProps` in the doc, but I think I just figured it out.
`toastProps` is for the "container".
`contentProps` is for the "ToastItem" child component.

**Comment by jerrywu001** [comment]
> I don't see anything about `contentProps` in the doc, but I think I just figured it out. `toastProps` is for the "container". `contentProps` is for the "ToastItem" child component.
> 
> Should probably add a contentProps exemple in the doc, I was confused when I dumped `\<pre\>{{ toastProps }}\</pre\>` inside my custom component

I will add a contentProps exemple in the doc

**Comment by jerrywu001** [comment]
From v0.2.7, see doc:

https://vue3-toastify.js-bridge.com/usage/pass-props-to-custom-component.html
