### ISSUE TITLE
Globally define custom icon by type

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#68]
Here is how it was handle in vue-toastification:
```js
import { TYPE } from 'vue-toastification';

import CheckIcon from '@/assets/svg/success.svg?inline';
import ErrorIcon from '@/assets/svg/error.svg?inline';
import InfoIcon from '@/assets/svg/info.svg?inline';
import WarningIcon from '@/assets/svg/warning.svg?inline';

const update = {
    toastDefaults: {
        [TYPE.DEFAULT]: {
            icon: InfoIcon,
        },
        [TYPE.INFO]: {
            icon: InfoIcon,
        },
        [TYPE.SUCCESS]: {
            icon: CheckIcon,
        },
        [TYPE.WARNING]: {
            icon: WarningIcon,
        },
        [TYPE.ERROR]: {
            icon: ErrorIcon,
        },
    },
};

export default function ({ app, beforeNuxtRender, nuxtState }, inject) {
        app.$toast.updateDefaults(update);
}

```

**Comment by jerrywu001** [comment]
I will improve the documentation, you can  use like this.

- main.ts

```ts
const CustomIcon = (props: IconProps) => {
  switch (props.type) {
    case 'info':
      return '🎈';
    case 'success':
      return '✌️';
    case 'error':
      return '🤣';
    case 'warning':
      return '😢';
    default:
      return undefined;
  }
};

app.use(
  Vue3Toasity,
  {
    icon: CustomIcon,
   // ...
  } as ToastContainerOptions,
);
```

**Comment by mrleblanc101** [comment]
I'm by no mean a TypeScript exert, so maybe I'm missunderstandning, but I think there is a type error in the code or your exemple is incorrect. I get this error:
> Type '(props: IconProps) => "👌" | "..." | "🎈" | "✌️" | "🤣" | "😢" | undefined' is not comparable to type 'IconType | undefined'.
But IconType is this:
> export declare type IconType = boolean | string | number | VNode | ((props: IconProps) => VNode) | DefineComponent<IconProps, {}, {}>;
I believe the part `(props: IconProps) => VNode` is incorrect because "👌" is not a VNode, but a string

**Comment by jerrywu001** [comment]
fixed from v0.2.7 @mrleblanc101 
https://vue3-toastify.js-bridge.com/usage/icons.html#custom-icons-globally

**Comment by mrleblanc101** [comment]
Awesome man 🙌

**Comment by mrleblanc101** [comment]
@jerrywu001 You can't override one specific icon tho !
You need to override them all, I wanted to override all of them except the spinner.
I'm trying to import the default spinner from the files, but it's not exported.

**Comment by jerrywu001** [comment]
> @jerrywu001 You can't override one specific icon tho ! You need to override them all, I wanted to override all of them except the spinner. I'm trying to import the default spinner from the files, but it's not exported.

???? Does it mean this?

```ts
import { VNodeIcon } from './icons.tsx';

createApp(App).use(
  Vue3Toasity,
  {
    icon: VNodeIcon, // use unified icon
  },
).mount('#app');
```

- toast.info
![image](https://github.com/user-attachments/assets/c5c85570-6639-473c-b4fe-48a8c99d4dab)

- toast.loading

![image](https://github.com/user-attachments/assets/76d4b84a-57c9-40cf-8867-01a4958f1ab8)

**Comment by mrleblanc101** [comment]
@jerrywu001 Not exacly, I want to override `default/info, success, warning, error` with different icons, but now I need to specify a `loading` icon too. I can't omit it, if I omit it there is no icon instead of falling back to the default.

**Comment by mrleblanc101** [comment]
Found a way in the meantime:
```js
import { Icon } from '#components';
import Vue3Toastify, { toast, type ToastContainerOptions, type IconProps, Icons } from 'vue3-toastify';
import 'vue3-toastify/dist/index.css';

const CustomIcon = (props: IconProps) => {
    switch (props.type) {
        case 'default':
            return h(Icon, { name: 'material-symbols:info-rounded', size: '32px' });
        case 'info':
            return h(Icon, { name: 'material-symbols:info-rounded', size: '32px' });
        case 'success':
            return h(Icon, { name: 'material-symbols:check-circle-rounded', size: '32px' });
        case 'warning':
            return h(Icon, { name: 'material-symbols:warning-rounded', size: '32px' });
        case 'error':
            return h(Icon, { name: 'material-symbols:report-rounded', size: '32px' });
        case 'loading':
            return h('div', { class: 'Toastify__spinner' });
        default:
            return undefined;
    }
};
```
