### ISSUE TITLE
Possibility to style with Tailwind

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#69]
I thought a custom component would allow me to do this, but I release the custom component (ToastItem) is a small part of the larger Toast component.
You can see how `@vueform/multiselect` handles Tailwind classes here: https://github.com/vueform/multiselect?tab=readme-ov-file#using-classes-prop

**Comment by jerrywu001** [comment]
you can use custom component instead, like:

![image](https://github.com/user-attachments/assets/7b097f0a-c61f-421c-b266-e0d2aa945e07)

- `Custom.vue`

```html
<template>
  <div>
    <el-button type="primary" class="bg-[#f60] text-white">
      Primary {{ name }}
    </el-button>
  </div>
</template>

<script setup lang="ts">
defineProps({
  name: {
    type: String,
    default: 'test',
  },
});
</script>
```

- invoke 

```ts
toast.loading(Custom, {
    contentProps: { name: 'sended' },
    expandCustomProps: true,
  });
```

**Comment by mrleblanc101** [comment]
This does not change the global CSS used by the theme.

**Comment by mrleblanc101** [comment]
@jerrywu001 For exemple, I want my toast to look like this.
Currently not possible with Tailwind, so I'm going to have to override the themes using normal CSS.
<img width="963" alt="Screenshot 2024-12-18 at 10 18 35 AM" src="https://github.com/user-attachments/assets/c0f3d9e9-5c30-49ef-8a2e-0ef12f7a000f" />
