### ISSUE TITLE
[Request] Smoother v-move animation

### ISSUE THREAD

**Issue by helixion** [jerrywu001/vue3-toastify#7]
Currently there doesn't seem to be a v-move animation set when the option of newest on top is selected. Instead of an animation where the older toasts snap to the beneath the newest one, would it be possible to get a smoother transition?

**Comment by jerrywu001** [comment]
> Currently there doesn't seem to be a v-move animation set when the option of newest on top is selected. Instead of an animation where the older toasts snap to the beneath the newest one, would it be possible to get a smoother transition?

Thanks for the suggestion and I would like to implement it sometime in the future. Then notify you.

Thanks again.
