### ISSUE TITLE
Why are the links to v0.1 not in english ?

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#71]
This bring you to the demo page, but for v0.1, the demo page is in english so the link should also be in english 🤔 
No ?

![Screenshot 2024-12-18 at 10 21 16 AM](https://github.com/user-attachments/assets/8733d97c-076f-4fa1-9174-2c6211ca5741)

**Comment by jerrywu001** [comment]
![image](https://github.com/user-attachments/assets/a39e815c-a898-43f7-a2b3-e968a3279304)

updated
