### ISSUE TITLE
How to use a `NuxtLink` inside custom Toast ?

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#72]
Currently, I get:
> [Vue warn]: Failed to resolve component: RouterLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

I think `vue-toastification` solved this using the `shareAppContext` config option.

**Comment by jerrywu001** [comment]
-main.ts

```ts
import { App, createApp } from 'vue';
import router from './routes';

import Vue3Toasity, { type ToastContainerOptions } from 'vue3-toastify';

import Root from './App.vue';

import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/reset.css';

const app = createApp(Root);

resolveGLobalComponents(app);

function resolveGLobalComponents(instance: App<Element>) {
  instance.use(Antd).use(router);
}

app.use(
  Vue3Toasity,
  {
    useHandler: resolveGLobalComponents,
    // rtl: true,
  } as ToastContainerOptions,
);

app.mount('#app');

```

**Comment by mrleblanc101** [comment]
I thought I saw that in the documentation, but can't find it anymore 🤔 
Also Nuxt is quite different from regular Vue / ant-design-vue.
I'll try to experiement tomorrow based on that, and maybe open a PR to document adding both `router-link` (vue-router) and `nuxt-link`.

**Comment by mrleblanc101** [comment]
Oh, it's on the homepage: https://vue3-toastify.js-bridge.com/
But Chrome history keep bringing me back to https://vue3-toastify.js-bridge.com/get-started/introduction.html
And the problem is that the homepage is not indexed by the search ! So I found no results using the search...

I think we should remove this crucial exemple from the homepage and move it to the `Usage` section of the documentation, with the other exemples. And add a Nuxt exemple once I figured out how.

Also note the typo in the section title `Registe global components (For example antd)` instead of `Register global components`

**Comment by mrleblanc101** [comment]
Also `useRender` is not documented under `API Reference`.
<img width="1784" alt="Screenshot 2024-12-19 at 10 20 23 PM" src="https://github.com/user-attachments/assets/acc362cd-b29b-46ac-bffe-0f7ae3fe48e9" />
<img width="1783" alt="Screenshot 2024-12-19 at 10 27 59 PM" src="https://github.com/user-attachments/assets/c6229812-185a-43b7-82bc-eea3e820d146" />
<img width="1778" alt="Screenshot 2024-12-19 at 10 28 06 PM" src="https://github.com/user-attachments/assets/f153912f-a704-4ca7-9614-1f999657d8d4" />

**Comment by mrleblanc101** [comment]
Wait a minute, we should probably make sure that everything in the project readme is also in the doc: 
https://github.com/jerrywu001/vue3-toastify

In fact, I think we should remove everything technical details from the README, and put it in the documentation instead.
